version: "3.9"

services:

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./config/dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env
    volumes:
      - ./test:/app/test
      - ./source:/app/source
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./config/.env
