"""empty message

Revision ID: 3c416442189d
Revises: ba3bd5875318
Create Date: 2024-06-30 16:12:54.557121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c416442189d'
down_revision = 'ba3bd5875318'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
