"""empty message

Revision ID: a360158cad56
Revises: 3c416442189d
Create Date: 2024-06-30 16:24:20.460059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a360158cad56'
down_revision = '3c416442189d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrator', sa.Column('nic_handle1', sa.String(length=255), nullable=True))
    op.add_column('registrator', sa.Column('nic_handle2', sa.String(length=255), nullable=True))
    op.add_column('registrator', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('registrator', sa.Column('city', sa.String(length=255), nullable=True))
    op.drop_column('registrator', 'last_name')
    op.drop_column('registrator', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrator', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrator', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('registrator', 'city')
    op.drop_column('registrator', 'website')
    op.drop_column('registrator', 'nic_handle2')
    op.drop_column('registrator', 'nic_handle1')
    # ### end Alembic commands ###
